### ISSUE TITLE
How to construct a mesh

### ISSUE THREAD

**Issue by quantumdot** [gradientspace/geometry3SharpDemos#2]
First, it looks like you have a great library here, thanks for all your work! I have the following data defining an isosurface mesh from another program and would like to build a mesh for spatial queries (e.x. ray intersection):

- `Vertices`: `float[n, 3]` where n = number of vertices and each row holds the coordinate of a vertex `[x y z]`
- `Triangles`: `int[n, 3]` where n = number of triangles and each row holds three indices to the vertices array
- `Normals`: `float[n, 3]` row holds the orientation `[x y z]` of a normal and corresponds to a vertex with the same row index

How do I efficiently create a `DMesh3` from this data? I assume that I then want to pass this `DMesh3` to an instance of `DMeshAABBTree3` in order to perform efficient ray intersection queries. Is this correct?

Ultimately, the problem I would like to solve is computing the relative radial position of a point inside the isosurface. Ex: `radial = dist(center, point) / dist(center, edge)` where `center` is the isosurface center of mass (already computed), `point` is a query point, and `edge` is the point on the isosurface that lies on the ray `(center, point)`.

**Comment by rms80** [comment]
rather than just answer here, I wrote a tutorial: [http://www.gradientspace.com/tutorials/2017/7/20/basic-mesh-creation-with-g3sharp](http://www.gradientspace.com/tutorials/2017/7/20/basic-mesh-creation-with-g3sharp)

Let me know if you still have any questions.

**Comment by quantumdot** [comment]
Wow, this is great! Thanks a lot!
