### ISSUE TITLE
Create surface from x,y,z surface points

### ISSUE THREAD

**Issue by Stevesy68** [gradientspace/geometry3SharpDemos#3]
I apologize in advance if this is addressed in a tutorial or forum or this shouldn't be asked here but I've been searching for hours and haven't found it. 
Is it possible to reconstruct a surface from X,Y,Z points (unstructured point cloud) to triangle  mesh with G3Sharp?

**Comment by rms80** [comment]
currently there is no obvious way to do this. There are some kinda hacky ways. And I may implement a new technique for doing this soon (you aren't the first to ask).

**Comment by Stevesy68** [comment]
Thank you for replying even if its not the answer I was looking for. I closed this one and re-posted in the main forum with some further detail.  I'm not trying to do full 3d it's 2.5d and I can control exactly where the points are taken on the XY plane.  Anyway, please review the scenario I posted in the other forum maybe it will limit how "hacky" I would have to be.
